### ISSUE TITLE
add capability to sort import statements

### ISSUE THREAD

**Issue by nlloyd** [delfoxie/EclipseJavaFormatter#1]
I believe this is distinct from the formatter mechanism in eclipse, but it would be AWESOME if you had an import sorting mechanism as well, potentially like the eclipse import sorter.

**Comment by delfoxie** [comment]
Hmm. I was looking to see if Eclipse had this exposed as a command line tool.  A fair amount of googling and api browsing hasn't turned up much.  My suspicion is that it is tied up with the auto-import feature (which is actually what would be awesome to have in SublimeJava).

Without auto-import, though, the sorting feature doesn't look too difficult to implement.

**Comment by nlloyd** [comment]
I wasn't thinking about anything using eclipse directly, but I am also thinking of putting in an auto-import mechanism into SublimeJava.  I have a lot of plans :-)

**Comment by delfoxie** [comment]
I just added a branch with import sorting.  It's a little screwy at the moment, but if you want to try it out, it's there.

**Comment by delfoxie** [comment]
Alright, it's in master and no longer screwy.  Or, at least, the screwiness that I saw is gone.
